# Generated by Django 6.0.6 on 2026-06-06 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "帖子",
                "verbose_name_plural": "帖子",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "用户资料", "verbose_name_plural": "用户资料"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="分类描述"),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="📝", max_length=10, verbose_name="图标"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="分类名称"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="网址名称"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.category",
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="正文内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("entertainment", "娱乐"),
                    ("games", "游戏"),
                    ("sport", "体育"),
                    ("technology", "科技"),
                    ("life", "生活"),
                ],
                default="entertainment",
                max_length=30,
                verbose_name="内容类型",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="封面图片链接"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="是否发布"),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="个人简介"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_author",
            field=models.BooleanField(default=True, verbose_name="是否为作者"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
