# Generated by Django 6.0.6 on 2026-06-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="views_count",
        ),
    ]
